"""SQLAlchemy 2.0 declarative base + shared mixins.

All ORM models import `Base` from here so Alembic's autogenerate sees them.
Imports of the actual models live in `api/models/__init__.py`.
"""

from __future__ import annotations

from datetime import datetime
from enum import Enum as PyEnum
from typing import Any
from uuid import UUID, uuid4

from sqlalchemy import DateTime, Enum as SAEnum, MetaData, func
from sqlalchemy.orm import DeclarativeBase, Mapped, declared_attr, mapped_column

# Naming convention so Alembic-autogenerated indexes / constraints have
# stable, predictable names across environments.
NAMING_CONVENTION = {
    "ix": "ix_%(table_name)s_%(column_0_name)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    """Project-wide declarative base."""

    metadata = MetaData(naming_convention=NAMING_CONVENTION)


class TimestampMixin:
    """Adds `created_at` and `updated_at` columns set by the DB."""

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )


def uuid_pk() -> Mapped[UUID]:
    """A UUID primary-key column with a Python-side default (uuid4)."""
    return mapped_column(primary_key=True, default=uuid4)


def pg_enum(enum_cls: type[PyEnum], name: str) -> SAEnum:
    """Build a `SAEnum` that stores the enum's `.value` strings (not member names).

    Using `values_callable` keeps the Postgres enum type in sync with the
    string values exposed in the API contract.
    """
    return SAEnum(
        enum_cls,
        name=name,
        values_callable=lambda obj: [e.value for e in obj],
        native_enum=True,
        create_constraint=True,
    )


__all__ = ["Base", "TimestampMixin", "uuid_pk", "pg_enum", "NAMING_CONVENTION"]
